version: 2.1
jobs:
  # check_squid_release:
  #   docker:
  #     - image: cimg/base
  #       auth:
  #         username: mydockerhub-user
  #         password: $DOCKERHUB_PASSWORD
  #   steps:
  #     - run: curl -s https://api.launchpad.net/1.0/ubuntu/+archive/primary\?ws.op\=getPublishedBinaries\&pocket\=Release\&binary_name\=squid\&exact_match\=true\&ordered_by_date\=true | jq '.entries|.[0].source_package_version'
  build-test:
    environment:
      IMAGE_NAME: zenman94/squid
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run: docker buildx build --platform $BUILDX_PLATFORMS --tag $IMAGE_NAME:latest .
      - run: docker push $IMAGE_NAME:latest
  build:
    environment:
      IMAGE_NAME: zenman94/squid
    docker:
      - image: cimg/base
    steps:
      - run: |
          curl -L \
          --output /usr/lib/docker/cli-plugins/docker-buildx \
          "https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64"
      - checkout
      - setup_remote_docker
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: |
          docker buildx build --push \
            --platform linux/arm64/v8,linux/amd64 \
            --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:$CIRCLE_TAG .

workflows:
  version: 2
  build-test:
    jobs:
      - build-test:
          filters:
            branches:
              only: master
  build-image:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
