version: 2.1

commands:

  configure-dockerhub:
    description: Configure Docker Hub access
    steps:
      - run:
          name: Configure Docker Hub
          command: |
            [ -z "$DOCKER_PASSWORD" ] && exit 0
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

  install-docker-buildx:
    description: Install Docker Buildx
    steps:
      - run:
          name: Install Docker Buildx
          command: |
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L "https://github.com/docker/buildx/releases/download/v0.8.1/buildx-v0.8.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx version
            sudo apt-get update && sudo apt-get install -y binfmt-support qemu-user-static
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker run --privileged --rm tonistiigi/binfmt --install arm64
            docker context create buildcontext
            docker buildx create buildcontext --use

jobs:
  build:
    environment:
      IMAGE_NAME: zenman94/squid
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - install-docker-buildx
      - configure-dockerhub
      - run: 
          name: Build and push container
          command: |
            docker buildx inspect --bootstrap
            docker buildx build --build-arg SQUID_VERSION=$CIRCLE_TAG --push --platform $BUILDX_PLATFORMS --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:$CIRCLE_TAG .
            
workflows:
  version: 2
  build-image:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

